version: '3'
services:

  sonarqube-init:
    build:
      dockerfile: sonarqube-init.Dockerfile
      context: configs/sonar
    volumes:
      - sonarqube-extensions:/opt/sonarqube/extensions

  sonar:
    depends_on:
      - sonarqube-init
      - sonardb
    environment: 
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
      - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL}
    image: ${SONARQUBE_DOCKER_IMAGE}
    logging: {'driver': 'json-file', 'options': {'tag': 'docker-sonar'}}
    ports: ['9000:9000']
    restart: always
    volumes: 
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - sonarqube-logs:/opt/sonarqube/logs 

  sonardb:
    environment: 
      - POSTGRES_USER=${SONARQUBE_JDBC_USERNAME}
      - POSTGRES_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
    image: ${POSTGRES_DOCKER_IMAGE}
    logging: {'driver': 'json-file', 'options': {'tag': 'docker-sonardb'}}
    restart: always
    volumes: 
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube-conf:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-bundled-plugins:
  sonarqube-logs:
  postgresql:
  postgresql_data:
